# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
# auto: true


title : 小葵的博客花园
tagline: cool coding girl
author : sunnygarden
name : sunnygarden
description: Android Developer, Google Fans, Like OpenSource
email : 630447712@qq.com
github : https://github.com/sunnygarden


production_url : http://sunnygarden.top

codepiano :
  version : 0.3.0 
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /posts.html
  categories_path : /categories.html
  tags_path : /posts.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  comments :
    provider : disqus
    disqus :
      short_name : sunnysblog
  analytics :
    provider : custom
  sharing :
    provider : false

markdown: kramdown
theme: minima